package KieRule;
import com.wipro.rtvs.Scm;
import com.wipro.rtvs.Rtvs;
import com.wipro.rule.ServiceMongo;
import java.util.List;
import com.wipro.rule.Team;
import com.wipro.rule.Achievements;
import com.wipro.rtvs.Sonar;

rule "RTVS"

when
rtvs:Rtvs(rigletName=="EDN141")
then
System.out.println("hello");
end;




rule "SCM"

when
scm:Scm(commitCount>2)
p:Team()
then
Achievements achievment=new Achievements();
p.setPoints(p.getPoints()+10);
achievment.setMetric("No. of commits per day");
achievment.setReward(10);
p.setAchievements(achievment);
end;


rule "Sonar"

when
sonar:Sonar(Integer.parseInt(criticalViolations)<15)
t:Team()
then
Achievements achievment=new Achievements();
t.setPoints(t.getPoints()+10);
achievment.setReward(10);
t.setAchievements(achievment);
end;



rule "Sonar_blocker"

when
sonar:Sonar(Integer.parseInt(blockerViolations)<12)
p:Team()
then
Achievements achievment=new Achievements();
p.setPoints(p.getPoints()+10);
achievment.setMetric("Blocker Violations");
achievment.setReward(10);
p.setAchievements(achievment);
end;

