package KieRule;
import com.wipro.rtvs.Scm;
import com.wipro.rtvs.Rtvs;
import com.wipro.rule.ServiceMongo;
import java.util.List;
import com.wipro.rule.Team;
import com.wipro.rule.Achievements;
import com.wipro.rtvs.Sonar;




rule "Sonar"

when
sonar:Sonar(Integer.parseInt(criticalViolations)<15)
t:Team()
then
Achievements achievment=new Achievements();
t.setPoints(t.getPoints()+4);
achievment.setReward(4);
achievment.setMetric("Critical violations for code base");
t.setAchievements(achievment);
end;



rule "Sonar_blocker"

when
sonar:Sonar(Integer.parseInt(blockerViolations)<12)
p:Team()
then
Achievements achievment=new Achievements();
p.setPoints(p.getPoints()+2);
achievment.setMetric("Blocker Violations");
achievment.setReward(2);
p.setAchievements(achievment);
end;




rule "SCM"

when
scm:Scm(commitCount>2)
p:Team()
then
Achievements achievment=new Achievements();
p.setPoints(p.getPoints()+10);
achievment.setMetric("No. of commits per day");
achievment.setReward(10);
p.setAchievements(achievment);
end;

